Добрый день, страничка сверстана. Посмотрите, пожалуйста.
pfrankov/kurmak-certs-layout pull request #1
Opened 2021-03-06 12:09 UTC by jusstes

Приветствую)
Изучаю верстку пару месяцев и была сложность с гридами, но это современный инструмент, которому нужно учиться. Спасибо за предоставленную возможность сверстать по макету. Я надеюсь на обратную связь.
С моей же стороны, мне не совсем ясно поведение страницы в диапазоне от ~950 до 1160. Можно было пойти двумя вариантами:
1) Уменьшить текст шрифта, но оставить прежний размер сертификата
2) Уменьшить размер сертификата, но оставить текст большим.
Предполагаю, что второй вариант предпочтительнее, поскольку страница претендует на Accessibility.
Ссылка на GH Pages.
Спасибо за внимание :)
https://jusstes.github.io/kurmak-certs-layout/

2021-03-06 20:21 UTC, pfrankov requested changes
Спасибо за вёрстку и ссылку на превью!

Скорее всего, нужно будет прикрутить сборку.

2021-03-06 20:21 UTC, pfrankov commented on pages/index.css
> +@import url(../vendor/normalize.css); /* знаю, что не приветствуется, но все же, что скажете? :) */
Скажу, что комментарии для обсуждения кода лучше оставлять прямо в своём PR.

2021-03-06 20:21 UTC, pfrankov commented on index.html
> +<html lang="ru">
Страница на английском, а в HTML стоит русский.

2021-03-06 20:21 UTC, pfrankov commented on index.html
> +  <meta name="author" content="Алексей Голодников">
Это лишнее

2021-03-06 20:21 UTC, pfrankov commented on index.html
> +  <meta name="description" content="Сертификат посвященный цифровой доступности">
Если description добавлен для SEO, то лучше указать конкретно: что за сертификат и чей он. Разумеется, с поправкой на английский язык.

2021-03-06 20:21 UTC, pfrankov commented on index.html
> +  <meta property="og:locale" content="ru_RU">
Отличная идея — добавить блок для шаринга в соцсетях.

2021-03-06 20:21 UTC, pfrankov commented on index.html
> +  <meta property="og:image" content=""> <!-- заполнить после публикации на GitHub Pages -->
Только его тоже нужно заполнить.

2021-03-06 20:21 UTC, pfrankov commented on index.html
> +  <!-- изначально контейнер page содержал 3 блока (header, main, footer),
Лучше было бы оставить блоки `header` и `main`; футера на этой странице нет.
Они более семантичны + создают особые области, по которым удобно перемещаться через скринридер.

2021-03-06 20:21 UTC, pfrankov commented on index.html
> +  <a href="https://kurmak.info/" class="header__title" target="_blank">kurmak.info</a>
`target="_blank"` — это плохая практика в любом случае.
Так и скажите всем, кто будет спорить: это пользователь должен решать, какую ссылку открывать в новом окне, а какую — в текущем.

Если всё же очень хочется открывать в новом, то нужно не забывать про `rel="noopener noreferrer"`: http://odinokun.com/2020-06-09-target-blank-silno-nedoocenennaya-uyazvimost-v-bezopasnosti.html

2021-03-06 20:21 UTC, pfrankov commented on pages/index.css
> +@import url(../fonts/fonts.css);
Импорты без пре/постпроцессинга загружают кучу файлов, замедляя рендеринг там, где можно было бы не замедлять.

Нужно конкатенировать (объединить) все стили в единый бандл с помощью webpack, gulp-таски, любого препроцессора: Sass, Less или Postcss.

2021-03-06 20:21 UTC, pfrankov commented on fonts/fonts.css
> +  src: url('./Inter-Regular.woff2') format('woff2'),
Первые доли секунды, пока грузится шрифт, он совсем не отображается. Самый простой способ этого избежать: https://web.dev/font-display/#how-to-avoid-showing-invisible-text

2021-03-06 20:21 UTC, pfrankov commented on blocks/main/__subtitle/main__subtitle.css
> +.main__subtitle {
Здесь должен быть другой шрифт: Abrakadabra. Он не бесплатный, поэтому нужно найти его бесплатную альтернативу.

2021-03-06 20:21 UTC, pfrankov commented on blocks/main/__subtitle/main__subtitle.css
> +  max-width: 625px; /* не очень нравится как выглядит этот блок в девтулз. с width выглядит лучше */
Правильно не нравится — он так и не должен выглядеть.

Обрати внимание, что при уменьшении размеров экрана, можно поймать такой размер, где текст вплотную прилипает к краям экрана:
![image](https://user-images.githubusercontent.com/584632/110219749-11b15b80-7ed2-11eb-87dd-9dade4e2845c.png)

2021-03-06 20:21 UTC, pfrankov commented on blocks/page/page.css
> +.page {
Лучше не навешивать такие классы, с изменением `display`, на `body`, а изолировать в отельные теги — потом может быть очень больно добавлять что-то на страницу.

2021-03-06 20:21 UTC, pfrankov commented on blocks/page/page.css
> +  grid-template-columns: repeat(7, 140px);
Сетка есть, но практические не используется. Вопрос: зачем нужна такая сетка? Может лучше сделать полезную сетку?

![image](https://user-images.githubusercontent.com/584632/110219163-a5812880-7ece-11eb-96b5-513ffbf83211.png)

2021-03-06 20:21 UTC, pfrankov commented on images/Combined_Shape.svg
> +<svg width="56" height="56" viewBox="0 0 56 56" fill="none" xmlns="http://www.w3.org/2000/svg">
Можно уменьшить размер SVG, с помощью SVGOMG: https://jakearchibald.github.io/svgomg/

2021-03-06 20:21 UTC, pfrankov commented on index.html
> +  <title>Цифровая доступность</title>
`title` обычно содержит контент из заголовка первого уровня

2021-03-06 20:21 UTC, pfrankov commented on index.html
> +    <h1 class="main__title">CERTIFICATE</h1>
Это не заголовок первого уровня.

2021-03-06 20:21 UTC, pfrankov commented on index.html
> +    <p class="main__subtitle">DIGITAL ACCESSIBILITY COURSE</p>
Параграф предполагает обилие текстового контента и не предназначен для нескольких отдельных слов. Здесь больше подойдёт заголовок первого уровня.

2021-03-06 20:21 UTC, pfrankov commented on index.html
> +    <article class="main__copyright">
Это не заметка, поэтому `article` здесь лишний. Для группировки можно просто использовать `div`

2021-03-06 20:21 UTC, pfrankov commented on index.html
> +      <p class="main__author">Completed by Sergey Shiryaev &#9989;</p>
Параграфы лучше заменить на что-то более нейтральное.

2021-03-06 20:21 UTC, pfrankov commented on index.html
> +  <img class="main__certificate" src="./images/certify_1.jpg" alt="Сертификат">
Отсутствуют размеры у картинки. Это вызывает падение метрики CLS: https://web.dev/optimize-cls/

2021-03-06 20:21 UTC, pfrankov commented on index.html
> +  <ul class="main__list">
Список для группы ссылок — необязательно, но хорошо*!
_* Только если ссылок больше двух. В противном случае, скринридер будет дольше читать информацию, что это список, и незрячим пользователям придётся всё это выслушивать._

2021-03-06 20:21 UTC, pfrankov commented on index.html
> +        src="./images/Combined_Shape.svg" alt="Email icon">
Ссылки и кнопки должны содержать глаголы, например, «Поделиться через email».
На всякий случай, напомню ещё раз про поправку на английский.

Название файла лучше исправить, а то в файловой структуре непонятно, что это за файл.

Всё это касается и других ссылок ниже.

2021-03-06 20:21 UTC, pfrankov commented on index.html
> +      <a href="#" class="main__links" target="_blank"><img class="main__images"
Хотелось бы реальную ссылку, пусть и на фейковый адрес.

2021-03-06 20:21 UTC, pfrankov commented on blocks/main/__time/main__time.css
> +    line-height: 24px;
Я бы избегал фиксированных размеров интерлиньяжа, а отталкивался от размера шрифта (`em`)

2021-03-06 20:21 UTC, pfrankov commented on blocks/header/__title/header__title.css
> +  font-size: 20px;
Вместо фиксированных размеров текста лучше использовать набор глобальных CSS Custom Properties.

2021-03-06 20:21 UTC, pfrankov commented on blocks/main/__certificate/main__certificate.css
> +  vertical-align: top; /* убираем лишние пиксели снизу картинки */
Вместо этого лучше использовать `display: block`. Там же натурально блочный элемент.

2021-03-07 04:29 UTC, jusstes commented on index.html
> +  <meta property="og:locale" content="ru_RU">
Спасибо за комментарий. Но раз страница действительно для англоговорящих людей, не лучше ли указать в 10й строке контент "en_EN"?

2021-03-07 11:40 UTC, pfrankov commented on index.html
> +  <meta property="og:locale" content="ru_RU">
Конечно же стоит

2021-03-13 12:59 UTC, jusstes commented on blocks/header/__title/header__title.css
> +  font-size: 20px;
Правильно ли я понял, что Вы рекомендуете для font-size использовать css-переменные?

2021-03-13 12:59 UTC, jusstes commented on index.html
> +      <p class="main__author">Completed by Sergey Shiryaev &#9989;</p>
Не смог придумать ничего лучше, чем h3. Но ведь это не заголовок 3го уровня?.. Я думал про figcaption, но он ведь подходит больше для описания к медиа-фрагментам? В общем, теряюсь в догадках.

2021-03-13 13:00 UTC, jusstes commented on blocks/page/page.css
> +  grid-template-columns: repeat(7, 140px);
Вы безусловно правы. Меня просто смутила сетка в фигме, пытался сверстать по этим колонкам. Сейчас ушел от этой идеи и сделал лучше.

2021-03-13 13:02 UTC, jusstes commented
Пока не разобрался с вебпаком, поэтому отправляю запрос с актуальными исправлениями. Если все будет более-менее ок, то добавлю вебпак (он ведь нужен в том числе и для вендорных префиксов?). И извиняюсь за долгие правки.

2021-03-14 13:44 UTC, pfrankov requested changes
Извиняться за долгие правки не нужно. Во всяком случае, не в Pull Request'е.
Ревьюер на каждый момент времени предполагает, что версия в Pull Request'е является самой последней, поэтому не стоит размазывать правки по куче коммитов или просить посмотреть незавершённую работу.
Идея разделения правок на отдельные коммиты в том, чтобы можно было откатить какую-то часть функциональности без проблем. Например, ты коммитишь фичу и к ней идут временные фиксы, которые потом могут или будут откатывать.

2021-03-14 13:44 UTC, pfrankov commented on blocks/header/__title/header__title.css
> +  font-size: 20px;
Да, всё верно. Зафиксировать все доступные размеры в `:root` помогает не плодить кучу похожих размеров: 12px, 13px, 14px

2021-03-14 13:44 UTC, pfrankov commented on blocks/main/__certificate/main__certificate.css
> +  width: 384px;
Без необходимости, лучше не фиксировать напрямую размеры картинок через CSS, а вписывать их в контейнеры нужных размеров. А ещё лучше, если размеры изображения будут установлены заранее, чтобы не уменьшать метрику CLS https://web.dev/optimize-cls/

2021-03-14 13:44 UTC, pfrankov commented on index.html
> +      <p class="main__share">Share</p>
Это не параграф

2021-03-14 13:44 UTC, pfrankov commented on index.html
> +        <h3 class="main__author">Completed by Sergey Shiryaev &#9989;</h3>
Это не заголовок третьего уровня, а просто текст

2021-03-14 13:44 UTC, pfrankov commented on index.html
> +        <h3 class="main__date">November 7, 2020</h3>
И этот. Это скорее `<time>`

2021-03-14 13:44 UTC, pfrankov commented on index.html
> +        <h3 class="main__time">5 weeks of study, 8 hours per week.</h3>
Это тоже не заголовок

2021-03-14 13:44 UTC, pfrankov commented on index.html
> +      <img class="main__certificate" src="./images/certify_1.jpg" alt="Сертификат">
Лучше убрать слово Сертификат вообще

2021-10-21 04:58 UTC, closed without merging