Roman Edigarev
pfrankov/kurmak-certs-layout pull request #5
Opened 2021-03-07 12:40 UTC by RomanEdigarev

Добрый день! Прошу дать ревью по выполненной верстке.  Заранее большое спасибо.
Ссылка на gh-pages: https://romanedigarev.github.io/kurmak-certs-layout/

2021-03-07 13:39 UTC, pfrankov requested changes
Спасибо за участие!

2021-03-07 13:39 UTC, pfrankov commented on README.md
> -# Вёрстка страницы для курса по Доступности
А нужно было выпиливать?

2021-03-07 13:39 UTC, pfrankov commented on public/images/facebook.svg
> +<svg width="56" height="56" viewBox="0 0 56 56" fill="none" xmlns="http://www.w3.org/2000/svg">
Для сжатия SVG иконок можно использовать SVGOMG: https://jakearchibald.github.io/svgomg/

2021-03-07 13:39 UTC, pfrankov commented on src/index.html
> +    <title>Kurmak</title>
По title должно быть возможно понять, на какой странице находится пользователь

2021-03-07 13:39 UTC, pfrankov commented on src/index.html
> +    <meta name="viewport" content="width=1440" />
Это похоже лишнее

2021-03-07 13:39 UTC, pfrankov commented on src/index.html
> +        <!--  Titles -->
Лучше не использовать комменты в HTML. Это такой признак: если тебе нужны комментарии в HTML или CSS — значит, скорее всего, ты делаешь что-то излишне сложное.

2021-03-07 13:39 UTC, pfrankov commented on src/index.html
> +          <h2 class="titles-wrapper__subtitle">certificate</h2>
Обратный ордер — это отлично!

2021-03-07 13:39 UTC, pfrankov commented on src/index.html
> +        <section class="information-section__name">
`section` обычно про большие блоки. Например, вся левая часть вполне справедливо `section`, а тут как-то странно.

2021-03-07 13:39 UTC, pfrankov commented on src/index.html
> +          <span>Completed by</span><br />
Не очень понял предназначение `span` здесь

2021-03-07 13:39 UTC, pfrankov commented on src/index.html
> +        <img src="./images/certify.png" alt="certificate" />
Нужно добавить атрибуты высоты и ширины, чтобы не вызывать уменьшения CLS https://web.dev/optimize-cls/

`alt` нужно или расширить или сделать пустым — из контекста будет понятно, что там внутри.

2021-03-07 13:39 UTC, pfrankov commented on src/index.html
> +          <p>Share</p>
Параграф предполагает много текстового контента. Это скорее заголовок.

2021-03-07 13:39 UTC, pfrankov commented on src/index.html
> +              ><img src="./images/mail.svg" alt="mail"
`alt` будет использоваться скринридером и будет зачитан, как "Mail, link". Будет понятнее, если ссылки будут читаться, как глаголы: "Share with email, link".

2021-03-07 13:39 UTC, pfrankov commented on src/index.html
> +            <a href="https://web.telegram.org"
Хотелось бы настоящих ссылок, хоть и с фейковыми данными.

2021-03-07 13:39 UTC, pfrankov commented on src/style.css
> +  height: 100vh;
Контент становится вплотную на маленьких окнах.
![image](https://user-images.githubusercontent.com/584632/110241439-c8105180-7f61-11eb-92f6-e93314b5fd8e.png)

2021-03-07 13:39 UTC, pfrankov commented on src/style.css
> +.information-section__name > span {
Можно ли без дополнительного элемента сделать всё то же самое?

2021-03-07 13:39 UTC, pfrankov commented on src/style.css
> +  box-shadow: 0 30px 100px 0 rgba(149, 252, 222, 0.1);
Круто, что нашёл!
Если приглядеться, в дизайне у этой тени немного другая высота. Я бы сделал псевдоэлементом, который бы положил под картинку.

2021-03-07 13:39 UTC, pfrankov commented on src/style.css
> +.links-for-sharing > div :nth-child(2n) {
Зачем такой сложный селектор? Нельзя ли обойтись более простым?

2021-03-07 13:39 UTC, pfrankov commented on src/style.css
> +    font-size: 12vw;
Интересное решение, но тогда нужно поддержать для всех элементов, а не только для заголовка
![image](https://user-images.githubusercontent.com/584632/110241564-8e8c1600-7f62-11eb-8ec3-b981ad1c433e.png)

2021-03-07 13:39 UTC, pfrankov commented on src/style.css
> +    font-size: 16px;
Я бы вынес размеры шрифтов отдельно в CSS-переменные.

2021-03-07 13:39 UTC, pfrankov commented on webpack.config.common.js
> +    new HtmlWebpackPlugin({
Это очень хорошо, но добавляет практически пустой js-файл. Нужно от него избавиться.

2021-03-07 13:39 UTC, pfrankov commented on src/index.html
> +    <link rel="preconnect" href="https://fonts.gstatic.com" />
Возможно, имеет смысл добавить `crossorigin` атрибут
https://www.cdnplanet.com/blog/faster-google-webfonts-preconnect/

2021-03-07 13:39 UTC, pfrankov commented on src/index.html
> +    <link
Кажется, это подключение шрифтов дублирует подключение строчкой ниже.

2021-03-07 13:39 UTC, pfrankov commented on src/index.html
> +          <span>November 7, 2020</span><br />
Время и дату можно сразу описывать через тег `time`

2021-03-08 08:34 UTC, RomanEdigarev commented on src/index.html
> +            <a href="https://web.telegram.org"
Можно подробнее, пожалуйста, что понимается под настоящей ссылкой. Спасибо.

2021-03-08 09:10 UTC, RomanEdigarev commented on src/style.css
> +  box-shadow: 0 30px 100px 0 rgba(149, 252, 222, 0.1);
Попробовал сделать через ::before и с blur.

2021-03-08 09:18 UTC, RomanEdigarev commented on src/style.css
> +.links-for-sharing > div :nth-child(2n) {
Не могу придумать более простой, если вдруг захочется добавить еще несколько ссылок для share

2021-03-08 10:05 UTC, RomanEdigarev commented on webpack.config.common.js
> +    new HtmlWebpackPlugin({
Можно подробнее, ведь если уберу эти плагины то webpack не будет создавать index.html  в папке dist?

2021-03-15 20:13 UTC, pfrankov commented on webpack.config.common.js
> +    new HtmlWebpackPlugin({
Верно, нужно сделать так, чтобы файл там оказывался, но лишний JS-файл не подключался.

2021-03-15 20:33 UTC, pfrankov requested changes
Кроме комментов также нужно решить проблему с поддержкой старых браузеров: например, сейчас финальный CSS содержит Custom Properties, которые в старых браузерах без фолбека просто не отобразятся.

И важный момент:
Ревьюер на каждый момент времени предполагает, что версия в Pull Request'е является самой последней, поэтому не стоит размазывать правки по куче коммитов или просить посмотреть незавершённую работу.
Идея разделения правок на отдельные коммиты в том, чтобы можно было откатить какую-то часть функциональности без проблем. Например, ты коммитишь фичу и к ней идут временные фиксы, которые потом могут или будут откатывать.

2021-03-15 20:33 UTC, pfrankov commented on src/index.html
> +            <a href="https://web.telegram.org"
Чтобы при нажатии она совершала целевое действие

2021-03-15 20:33 UTC, pfrankov commented on src/index.html
> +          <h3>Share</h3>
Заголовки должны выстраивать иерархию документа. Сейчас получается так:
```
Digital Accessibility Course
    certificate
        Share
```

2021-03-15 20:33 UTC, pfrankov commented on src/style.css
> +  width: 100%;
Поскольку картинка является инлайно-блоковым элементом — она будет слегка неправильно позиционироваться. Лучше сделать её просто блоковой, когда она используется не в тексте.

2021-03-15 20:33 UTC, pfrankov commented on src/style.css
> +  width: 123.2%;
Такое позиционирование из-за неровных процентов выглядит не очень надёжно. Я бы рекомендовал центрировать более надёжно.

2021-03-15 20:33 UTC, pfrankov commented on src/style.css
> +  filter: blur(100px);
Фильтр `blur` ест много ресурсов CPU (а в данном случае оно будет считаться чисто на CPU). Есть более дешёвая альтернатива, которую я предлагаю обдумать: как нарисовать размытый фон за элементом без `filter`.

2022-04-15 15:22 UTC, closed without merging